#!/usr/bin/env python3
"""Render Homebrew/Scoop manifests from the release's archive checksums."""
import json
import pathlib
import re
import sys


def render(tag, checksums, tap, bucket):
    if not re.fullmatch(r"v[0-9]+\.[0-9]+\.[0-9]+(?:-[A-Za-z0-9.-]+)?", tag):
        raise ValueError("expected a release version tag")
    hashes = {}
    for line in pathlib.Path(checksums).read_text().splitlines():
        digest, name = line.split()
        if not re.fullmatch(r"[a-fA-F0-9]{64}", digest) or name in hashes:
            raise ValueError("invalid or duplicate checksum")
        hashes[name] = digest.lower()
    base = f"https://github.com/useteploy/teploy-cli/releases/download/{tag}"
    lines = ['# typed: false', '# frozen_string_literal: true', '',
             '# Generated by teploy-cli scripts/render-distribution.py.',
             'class Teploy < Formula',
             '  desc "Zero-downtime Docker deploys to any server via SSH"',
             '  homepage "https://github.com/useteploy/teploy-cli"',
             '  license "MIT"']
    for platform, os_name in [('macos', 'darwin'), ('linux', 'linux')]:
        lines.extend(['', f'  on_{platform} do'])
        for cpu, arch in [('intel', 'amd64'), ('arm', 'arm64')]:
            asset = f'teploy_{os_name}_{arch}.tar.gz'
            lines.extend([f'    if Hardware::CPU.{cpu}? && Hardware::CPU.is_64_bit?',
                          f'      url "{base}/{asset}"',
                          f'      sha256 "{hashes[asset]}"', '',
                          '      define_method(:install) do',
                          '        bin.install "teploy"', '      end', '    end'])
        lines.append('  end')
    lines.extend(['', '  test do', '    assert_match version.to_s, shell_output("#{bin}/teploy version")', '  end', 'end', ''])
    manifest = {'version': tag[1:], 'architecture': {},
                'homepage': 'https://github.com/useteploy/teploy-cli',
                'license': 'MIT', 'description': 'Zero-downtime Docker deploys to any server via SSH'}
    for key, arch in [('64bit', 'amd64'), ('arm64', 'arm64')]:
        asset = f'teploy_windows_{arch}.zip'
        manifest['architecture'][key] = {'url': f'{base}/{asset}', 'bin': ['teploy.exe'], 'hash': hashes[asset]}
    # Finish validation of the whole matrix before writing either destination.
    pathlib.Path(tap, 'teploy.rb').write_text('\n'.join(lines))
    pathlib.Path(bucket, 'teploy.json').write_text(json.dumps(manifest, indent=4)+'\n')


if __name__ == '__main__':
    if len(sys.argv) != 5:
        raise SystemExit('usage: render-distribution.py <tag> <checksums> <tap-dir> <bucket-dir>')
    render(*sys.argv[1:])
